image: maven:latest
variables:
  SONAR_TOKEN: "748c430939dafbb7259e9fa803ff55cb3b41b459"
  SONAR_HOST_URL: "https://sonar.marco-hajek.me"
  GIT_DEPTH: 0
sonarqube-check:
  before_script:
    - export MAVEN_CLI_OPTS="-s ${MAVEN_CLI_OPTS_FILE} --batch-mode"
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.qualitygate.wait=true
    - mvn $MAVEN_CLI_OPTS deploy
  allow_failure: false
  only:
    - merge_requests
    - master